var Operation = {};
//中文
function getZhLanguage() {
        Operation = {
                //ui字段
                //通用
                ui_loading: '正在加载...',
                ui_back: '返回',
                ui_cancel: '取消',
                ui_search: '搜索',
                ui_select: '查询',
                ui_perday: '上一日',
                ui_nextday: '下一日',
                ui_lastmonth: '上一月',
                ui_nextmonth: '下一月',
                ui_date: '日期',
                ui_to: '至',
                ui_today: '当日',
                ui_yestoday: '昨日',
                ui_themonth: '当月',
                ui_permonth: '上月',
                ui_theweek: '本周',
                ui_perweek: '上周',
                ui_startdate: '起始日期',
                ui_enddate: '截止日期',
                ui_all: '全部',
                ui_nodata: '暂无相关数据',
                code_fail: '服务器异常',
                ui_maxval: '最大值',
                ui_minval: '最小值',
                ui_avgval: '平均值',
                ui_newValue: '最新值',
                ui_val: '值',
                ui_time: '时间',
                ui_selectDate: '选择日期',
                ui_confirm: '确定',
                ui_downupdate: '下拉刷新',
                ui_freedupdate: '释放更新',

                //页面
                //事件
                ui_watchposition: '监测点',
                ui_type: '类型',
                ui_metername: '仪表名称',
                ui_paramname: '参数名称',
                ui_meterholder: '请输入仪表名称',
                ui_paramholder: '请输入参数名称',
                ui_highalarm: '高限报警',
                ui_higheralarm: '高高限报警',
                ui_lowalarm: '低限报警',
                ui_loweralarm: '低低限报警',
                ui_alarmremove: '报警恢复',
                ui_alarmvalue: '报警值',
                ui_limitvalue: '限定值',
                ui_meterid: '仪表编号',
                ui_dateselecttip: '请选择正确的查询时间',
                ui_deviceid: '设备编号',
                ui_devicetip: '请输入设备编号',
                //电力
                ui_larger: '放大',
                ui_smaller: '缩小',
                ui_monthmaxkw: '当月最大需量',
                ui_starttime: '发生时间',
                ui_eleckind: '电力类别',
                ui_p: '有功功率',
                ui_i: '电流',
                ui_u: '相电压',
                ui_ul: '线电压',
                ui_ffr: '频率',
                ui_q: '无功功率',
                ui_s: '视在功率',
                ui_sum: '总',
                ui_a: 'A相',
                ui_b: 'B相',
                ui_c: 'C相',
                ui_pf: '功率因数',
                //电量
                ui_dayreport: '日报',
                ui_monthreport: '月报',
                ui_yearreport: '年报',
                ui_dayCurve: '日曲线',
                ui_monthCurve: '月曲线',
                ui_yearCurve: '年曲线',
                ui_summary: '合计',
                ui_elecval: '电量',
                ui_elecpriceval: '电费',
                ui_unit: '单位',
                ui_toelecval: '按电量',
                ui_toelecmoney: '按电费',
                ui_donut: '当月占比环形图',
                ui_totalsum: '总计',
                ui_yuan: '元',
                ui_jian: '尖',
                ui_feng: '峰',
                ui_ping: '平',
                ui_gu: '谷',
                ui_proportion: '当月占比',
                ui_consumeelecval: '用电量',
                ui_startval: '起始数值',
                ui_endval: '截止数值',
                ui_minusval: '差值',
                //平均功率因素
                ui_eqi: "正向有功电度",
                ui_eql: "正向无功电度",
                ui_pf: "平均功率因素",
                ui_epe: "反向有功电度",
                ui_eqc: "反向无功电度",
                //电能质量
                ui_iaharm: 'A相电流谐波',
                ui_ibharm: 'B相电流谐波',
                ui_icharm: 'C相电流谐波',
                ui_uaharm: 'A相电压谐波',
                ui_ubharm: 'B相电压谐波',
                ui_ucharm: 'C相电压谐波',
                ui_choose: '选择',
                ui_totalharm: '总谐波',
                ui_numharm: '次谐波含量',
                ui_IUnB: '电流三相不平衡度',
                ui_UUnB: '电压三相不平衡度',
                //电气安全
                ui_chart: '图表',
                ui_data: '数据',
                ui_temp: '温度',
                ui_cabtemp: '线缆温度',
                ui_collecttime: '采集时间',
                ui_leakI: '漏电流',
                //环境
                ui_humi: '湿度',
                //报表
                ui_power: '功率',
                ui_activepower: '有功功率',
                ui_reactivepower: '无功功率',
                ui_apparentpower: '视在功率',
                ui_unbalance: '不平衡度',
                ui_uharm: '电压谐波',
                ui_Iharm: '电流谐波',
                ui_uub: '电压三相不平衡度',
                ui_cub: '电流三相不平衡度',
                ui_uahr: 'A相电压总谐波含有率',
                ui_ubhr: 'B相电压总谐波含有率',
                ui_uchr: 'C相电压总谐波含有率',
                ui_iahr: 'A相电流总谐波含有率',
                ui_ibhr: 'B相电流总谐波含有率',
                ui_ichr: 'C相电流总谐波含有率',
                ui_theperiod: '本期',
                ui_sameperiod: '同期',
                ui_month: '月份',
                ui_samepercent: '同比',
                ui_totalsamepercent: '累计同比',
                ui_byday: '按日',
                ui_byweek: '按周',
                ui_bymonth: '按月',
                ui_consumeelec: '用电',
                ui_addval: '增加值',
                ui_mom: '环比',
                ui_timeInter: '时间间隔',
                ui_oneMin: '一分钟',
                ui_fiveMin: '五分钟',
                ui_FifteenMin: '十五分钟',
                ui_halfHour: '半小时',
                ui_oneHour: '一小时',
                ui_CircuitName: '回路',

                //变压器
                ui_transstatus: '变压器状态',
                ui_transload: '负荷',
                ui_ratedpower: '额定功率',
                ui_szpower: '视在功率',
                ui_loadrate: '负荷率',
                ui_ygpower: '有功功率',
                ui_wgpower: '无功功率',
                ui_yspower: '功率因数',
                ui_dyzdxl: '当月最大需量',
                ui_Ia: 'A相电流',
                ui_Ib: 'B相电流',
                ui_Ic: 'C相电流',
                ui_uab: 'Uab线电压',
                ui_ubc: 'Ubc线电压',
                ui_uca: 'Uca线电压',
                ui_voltage: '电压',
                ui_tempa: 'A相绕组温度',
                ui_tempb: 'B相绕组温度',
                ui_tempc: 'C相绕组温度',
                ui_oilTemp: '油浸温度',
                ui_noise: '噪声',
                ui_nowpower: '视在',
                ui_haspower: '有功',
                ui_nopower: '无功',
                ui_tempLine: '绕阻温度',
                ui_trans: '变压器',
                ui_discharge: "局部放电",
                ui_yy: "年",
                ui_mm: "月",
                ui_dd: "日",
                ui_hh: "时",
                ui_min: "分",

                //网关通讯
                ui_gate_id: "编号",
                ui_gate_name: "名称",
                ui_gate_type: "型号",
                ui_gate_uptime: "最后上传时间",
                ui_gate_collecttime: "最后采集时间",
                ui_gate_status: "状态",
                //仪表通讯
                ui_meter_gateway: "网关",
                ui_meter_COM: "串口",
                ui_meter_address: "仪表地址",
                ui_meter_name: "仪表名称",
                ui_meter_status: "通讯状态",
                ui_meter_offtime: "中断时间",
                ui_meter_collecttime: "最后采集时间",
                ui_meter_sumtime: "累计时间",
                ui_meter_showdis: "仅显示断线状态",

                //code码
                code_200: '请求成功，插入成功',
                code_201: '主外键异常',
                code_401: '需要客户端进行身份验证，需要客户端登录',
                code_105: '新增项不允许出现在包含设备设备详情或者巡检项详情的项下',
                code_101: '请删除子项',
                code_500: '服务异常',
                code_1000: '数据库pagecustom 表数据异常',
                code_10001: '信息填写有误',
                code_300: 'appKey重复',
                code_301: '文件上传失败',
                code_302: '请添加图片',
                code_303: '删除失败，没有此图片',
                code_107: '新增项业务类型需要与父级业务类型一致',
                code_108: '没有此菜单',
                code_109: '此菜单未初始化排序值',
                code_120: '没有可改变的菜单',
                code_125: '更新视频信息错误',
                code_126: '删除视频信息错误',
                code_127: '文件找不到',
                code_128: '启用的版本出错',
                code_129: '没有此id的版本',
                code_130: '更新失败',
                code_140: '删除安卓版本信息失败',
                code_141: '插入安卓版本信息失败',
                code_142: '数据库api版本数据出现错误',
                code_143: '不支持此设备',
                code_0: '登录失败',
                code_1: '获取用户错误，请重新登录',
                code_145: '反馈提交失败，请重新提交',
                code_146: '更新用户信息失败',
                code_147: '没有权限，请去配置权限',
                code_304: '请输入fSubid',
                code_305: '变电所已存在',
                code_306: '该变电所的编号或名称已存在',
                code_307: '数据初始化失败',
                code_308: '删除失败',
                code_309: '增加失败',
                code_310: '不是任务管理员',
                code_144: '请检查用户名和用户密码，登录失败',
                code_311: '不在此任务人员清单中',
                code_312: '请先签到',
                code_313: '此账号没有权限签名',
                code_314: '重复签到',
                code_315: '当前变电所没有缺陷',
                code_316: '当前没有设备',
                code_317: '当前变电所没有设备',
                code_318: '当前任务已经有巡检单',
                code_319: '负责人不能是执行人',
                code_320: '当前角色及其下级角色下存在用户',
                code_321: '当前用户组及其下级用户组下存在用户',
                code_322: '当前组织机构及其下级组织机构下存在变电所',
                code_323: '当前组织机构及其下级组织机构下存在角色',
                code_324: '当前组织机构及其下级组织机构下存在用户组',
                code_325: '当前区域及其下级区域下存在变电所',
                code_326: 'H5文件上传失败',
                code_327: '插入失败，该公司名称已存在',
                code_328: '插入失败，请重试（公司编号重复）',
                code_329: '请先添加文档',
                code_330: '日期格式化失败',
                code_331: '文件名已经存在',
                code_332: '文件大小不能超过10M',
                code_333: '数据库记录删除失败',
                code_334: '文件不存在',
                code_335: '该用户被禁用，请通知管理员开启使用权限',
                code_336: '不能禁用当前登录用户',
                code_700: '刷新token',
                code_205: '该设备存在记录',
                code_338: '用户名已存在',
                code_339: '萤石云appKey不存在',
                code_340: '萤石云appKey和appSecret不匹配',
                code_341: '网络配置错误',
                code_342: '自定义名称重复',
                code_343: '自定义报表计算项名称已存在',
                code_344: '该变电所下网关名称已经存在',
                code_345: '插入失败，网关代码重复',
                code_346: '萤石云appKey不能为空',
                code_347: '萤石云appSecret不能为空',
                code_600: '您使用的软件授权已过期',
                code_348: '当前用户没有变电所权限',
                code_349: '此变电所下已经有该仪表名称',
                code_350: '该变电所已经有该仪表code码',
                code_351: '该变电所已经有该仪表名称',
                code_352: '该回路编号已经存在',
                code_353: '该变压器编号已存在',
                code_354: 'admin角色名称不能修改',
                code_355: 'admin角色不能删除',
                code_356: 'admin用户登录名不能修改',
                code_357: 'admin用户不能删除',
                code_358: '删除失败，请登录有管理员权限的账号',
                code_359: '用户登录名已存在',
                code_360: '首页当前配置已为默认配置',
                code_361: '未配置萤石云appkey与secret信息',
                code_362: '该文档类别已存在',
                code_363: '当前用户未配角色',
                code_364: '非admin角色，操作权限不足',
                code_365: '该变电所没有组织机构',
                code_366: '变电所数量达到上限',
                code_367: '仪表数量达到上限',
                code_368: '没有此变电所',
                code_369: '没有查询到该变电所的组织机构信息',
                code_370: 'admin用户不能被禁用',
                code_371: '不能修改admin用户的组织机构或角色',
                code_372: '用户没有所选的全部变电所',
                code_373: '该模板及其下级模板已有变电所在使用',
                code_374: '该变电所编号超出范围，不能使用自动生成',
                code_375: '系统中存在编号为10109999变电所，无法自动生成，请联系管理员',
                code_376: '该变电所下，该网关下的仪表编号已存在',
                code_5000: '请求失败，服务器异常',
                code_377: '该变电所id可用',
                code_378: '该变电所id不可用',
                code_379: '该条数据主键已存在',
                code_380: '设备重名',
                code_381: '该变电所没有设备分组',
                code_382: '该变电所当前设备分组下已存在同名设备，建议修改',
                code_other: '操作失败',

        }
}

//英文
function getEnLanguage() {
        Operation = {

                ui_loading: 'Loading...',
                ui_back: 'Back',
                ui_cancel: 'Cancel',
                ui_search: 'Search',
                ui_select: 'Inquire',
                ui_perday: 'Last day',
                ui_nextday: 'Next day',
                ui_lastmonth: 'Last month',
                ui_nextmonth: 'Next month',
                ui_date: 'date',
                ui_to: 'to',
                ui_today: 'Today',
                ui_yestoday: 'Yesterday',
                ui_themonth: 'ThisMon.',
                ui_permonth: 'LastMon.',
                ui_theweek: 'This week',
                ui_perweek: 'Last week',
                ui_startdate: 'StartDate',
                ui_enddate: 'Deadline',
                ui_all: 'All',
                ui_nodata: 'No relevant data',
                code_fail: 'Server exception',
                ui_maxval: 'Maximum',
                ui_minval: 'Minimum',
                ui_avgval: 'Average',
                ui_newValue: 'Latest',
                ui_val: 'value',
                ui_time: 'time',
                ui_selectDate: 'Select date',
                ui_confirm: 'Confirm',
                ui_downupdate: 'Pull down to refresh',
                ui_freedupdate: 'Release update',

                ui_watchposition: 'MonitorPoint',
                ui_type: 'Type',
                ui_metername: 'Meter',
                ui_paramname: 'Param',
                ui_meterholder: 'Please enter a Metername',
                ui_paramholder: 'Please enter a Paramname',
                ui_highalarm: 'High limit Alarm',
                ui_higheralarm: 'High-high limit alarm',
                ui_lowalarm: 'Low alarm',
                ui_loweralarm: 'Low-low limit alarm',
                ui_alarmremove: 'Alarm recovery',
                ui_alarmvalue: 'Alarm',
                ui_limitvalue: 'Limit',
                ui_meterid: 'MeterId',
                ui_dateselecttip: 'Please select the correct query time',
                ui_deviceid: 'DeviceId',
                ui_devicetip: 'Please enter the DeviceId',
                ui_larger: 'Larger',
                ui_smaller: 'Narrow',
                ui_monthmaxkw: 'Month maximum demand',
                ui_starttime: 'OccurTime',
                ui_eleckind: 'ElecType',
                ui_p: 'Active Power',
                ui_i: 'Electric current',
                ui_u: 'Phase voltage',
                ui_ul: 'Line voltage',
                ui_ffr: 'frequency',
                ui_q: 'Reactive power',
                ui_s: 'Inspecting power',
                ui_sum: 'total',
                ui_a: 'A phase',
                ui_b: 'B Phase',
                ui_c: 'C Phase',
                ui_pf: 'Power Factor',
                ui_dayreport: 'Daily',
                ui_monthreport: 'Monthly',
                ui_yearreport: 'Yearly',
                ui_dayCurve: 'Daily',
                ui_monthCurve: 'Monthly',
                ui_yearCurve: 'Yearly',
                ui_summary: 'total',
                ui_elecval: 'Power',
                ui_elecpriceval: 'Electricity fee',
                ui_unit: 'unit',
                ui_toelecval: 'By electricity',
                ui_toelecmoney: 'By electricity',
                ui_donut: 'Month accounting Donut',
                ui_totalsum: 'total',
                ui_yuan: '￥',
                ui_jian: 'sharp',
                ui_feng: 'peak',
                ui_ping: 'flat',
                ui_gu: 'valley',
                ui_proportion: 'Month accounting',
                ui_consumeelecval: 'energy used',
                ui_startval: 'Start Value',
                ui_endval: 'Cut-off value',
                ui_minusval: 'Difference',
                ui_iaharm: 'A phase current harmonics',
                ui_ibharm: 'B phase current harmonics',
                ui_icharm: 'C phase current harmonics',
                ui_uaharm: 'A phase voltage harmonics',
                ui_ubharm: 'B phase voltage harmonics',
                ui_ucharm: 'C phase voltage harmonics',
                ui_choose: 'choose',
                ui_totalharm: 'Total Harmonic',
                ui_numharm: 'Harmonic content',
                ui_IUnB: 'Current imbalance',
                ui_UUnB: 'Voltage imbalance',
                ui_chart: 'chart',
                ui_data: 'data',
                ui_temp: 'Temp',
                ui_cabtemp: 'CabTemp',
                ui_collecttime: 'Collect',
                ui_leakI: 'Leak I',
                ui_humi: 'Humi',
                ui_power: 'power',
                ui_activepower: 'Active Power',
                ui_reactivepower: 'Reactive power',
                ui_apparentpower: 'Inspecting power',
                ui_unbalance: 'Unbalance',
                ui_uharm: 'Voltage harmonics',
                ui_Iharm: 'Current harmonics',
                ui_uub: 'Voltage imbalance',
                ui_cub: 'Current imbalance',
                ui_uahr: 'A Phase voltage total harmonic ratio',
                ui_ubhr: 'B Phase voltage total harmonic ratio',
                ui_uchr: 'C Phase voltage total harmonic ratio',
                ui_iahr: 'A phase current total harmonic ratio',
                ui_ibhr: 'B phase current total harmonic ratio',
                ui_ichr: 'C phase current total harmonic ratio',
                ui_theperiod: 'This period',
                ui_sameperiod: 'Same period',
                ui_month: 'month',
                ui_samepercent: 'Year',
                ui_totalsamepercent: 'YoY',
                ui_byday: 'Daily',
                ui_byweek: 'Weekly',
                ui_bymonth: 'Monthly',
                ui_consumeelec: 'Elec.',
                ui_addval: 'Value Added',
                ui_mom: 'MoM',
                ui_transstatus: 'Transformer State',
                ui_transload: 'load',
                ui_ratedpower: 'RP',
                ui_szpower: 'S',
                ui_loadrate: 'LF',
                ui_ygpower: 'P',
                ui_wgpower: 'Q',
                ui_yspower: 'PF',
                ui_dyzdxl: 'MD',
                ui_Ia: 'Ia',
                ui_Ib: 'Ib',
                ui_Ic: 'Ic',
                ui_uab: 'Uab',
                ui_ubc: 'Ubc',
                ui_uca: 'Uca',
                ui_voltage: 'Voltage',
                ui_tempa: 'TempA',
                ui_tempb: 'TempB',
                ui_tempc: 'TempC',
                ui_oilTemp: 'OilTemp',
                ui_noise: 'Noise',
                ui_nowpower: 'S',
                ui_haspower: 'P',
                ui_nopower: 'Q',
                ui_tempLine: 'Temp',
                ui_trans: 'transformer',
                ui_discharge: "Discharge",
                ui_yy: "Y",
                ui_mm: "M",
                ui_dd: "D",
                ui_hh: "H",
                ui_min: "m",

                //网关通讯
                ui_gate_id: "Number",
                ui_gate_name: "Name",
                ui_gate_type: "Type",
                ui_gate_uptime: "LastUploadTime",
                ui_gate_collecttime: "LastCollectionTime",
                ui_gate_status: "Status",
                //仪表通讯
                ui_meter_gateway: "Gateway",
                ui_meter_COM: "Serial",
                ui_meter_address: "MeterAddr",
                ui_meter_name: "Metername",
                ui_meter_status: "ComStatus",
                ui_meter_offtime: "OffTime",
                ui_meter_collecttime: "Lastcollecttime",
                ui_meter_sumtime: "TotalTime",
                ui_meter_showdis: "Only Show dis",

                //平均功率因素
                ui_eqi: "Positive Active Energy",
                ui_eql: "Positive Reactive Energy",
                ui_pf: "Average power factor",
                ui_epe: "Reverse Active Energy",
                ui_eqc: "Reverse Reactive Energy",
                ui_timeInter: 'TimeInterval',
                ui_oneMin: 'One minutes',
                ui_fiveMin: 'Five minutes',
                ui_FifteenMin: 'Fifteen minutes',
                ui_halfHour: 'half Hour',
                ui_oneHour: 'One Hour',
                ui_CircuitName: 'CircuitName',
                //code码
                code_200: 'Request succeeds, insert success',
                code_201: 'Primary foreign key exception',
                code_401: 'The client needs to be authenticated, the client needs to log',
                code_105: 'New items are not allowed in the entry contains details of equipment or inspection equipment item details',
                code_101: 'Please delete the child',
                code_500: 'Service Exception',
                code_1000: 'Pagecustom database table data anomalies',
                code_10001: 'Information filled in incorrectly',
                code_300: 'appKey repeat',
                code_301: 'File upload failed',
                code_302: 'Please add a picture',
                code_303: 'Delete failed, not this picture',
                code_107: 'New item type of business needs to be consistent with the parent service type',
                code_108: 'Without this menu',
                code_109: 'This menu is not initialized sort value',
                code_120: 'There is no change in the menu',
                code_125: 'Error updating video',
                code_126: 'Delete video error',
                code_127: 'File Not Found',
                code_128: 'Enabled version of the error',
                code_129: 'There is no version of this id',
                code_130: 'Update failed',
                code_140: 'Failed to delete Android version information',
                code_141: 'Plug Ruan Zhuo version information failed',
                code_142: 'Api version of the database data errors',
                code_143: 'This device is not supported',
                code_0: 'Login failed',
                code_1: 'Obtain user error, please sign in again',
                code_145: 'Failure to submit feedback, please resubmit',
                code_146: 'Failed to update user information',
                code_147: 'Do not have permission, please go to configure permissions',
                code_304: 'Please enter fSubid',
                code_305: 'Substation already exists',
                code_306: 'Number or name of the substation already exists',
                code_307: 'Data initialization failed',
                code_308: 'failed to delete',
                code_309: 'Increase failure',
                code_310: 'Not a task manager',
                code_144: 'Check the user name and password, the login fails',
                code_311: 'This task is not in the list of staff',
                code_312: 'Please sign',
                code_313: 'This account does not have permission signature',
                code_314: 'Repeat sign',
                code_315: 'The current substation is not defective',
                code_316: 'There are currently no devices',
                code_317: 'There is no equipment in the current substation',
                code_318: 'The current mission has a single inspection',
                code_319: 'It is not responsible for the executor',
                code_320: 'Currently exist under the user role and its subordinate role',
                code_321: 'The presence of the user currently subordinate user group and user group',
                code_322: 'The presence of substations under the current organization and its subordinate organizations',
                code_323: 'The presence of the organization and its subordinate role under the current organizational structure',
                code_324: 'User groups exist under the current organization and its subordinate organizations',
                code_325: 'Substation region exists under the current region and its subordinate',
                code_326: 'H5 file upload failed',
                code_327: 'Insert fails, the company name already exists',
                code_328: 'Insert failed, please try again (Company Number repeat)',
                code_329: 'Please add a document',
                code_330: 'Date formatting failed',
                code_331: 'Filename already exists',
                code_332: 'File size can not exceed 10M',
                code_333: 'Failed to delete database records',
                code_334: 'file does not exist',
                code_335: 'The user is disabled, please notify the administrator open permissions',
                code_336: 'You can not disable the currently logged on user',
                code_700: 'Refresh token',
                code_205: 'The device already exists',
                code_338: 'Username already exists',
                code_339: 'EZVIZ appKey does not exist',
                code_340: 'EZVIZ appKey and appSecret do not match',
                code_341: 'Network configuration error',
                code_342: 'Repeat custom name',
                code_343: 'Custom report calculated item name already exists',
                code_344: 'This substation gateway name already exists',
                code_345: 'Insertion fails, the gateway code repeat',
                code_346: 'EZVIZ appKey can not be empty',
                code_347: 'EZVIZ appSecret can not be empty',
                code_600: 'You use software license has expired',
                code_348: 'The current user does not have permission to substation',
                code_349: 'This substation has been the instrument name',
                code_350: 'The substation has been the instrument code code',
                code_351: 'The substation has been the instrument name',
                code_352: 'The loop number already exists',
                code_353: 'The transformer number already exists',
                code_354: 'admin role names can not be modified',
                code_355: 'admin role can not be deleted',
                code_356: 'admin user login name can not be modified',
                code_357: 'admin users can not delete',
                code_358: 'Deletion failed, please log in with administrator privileges account',
                code_359: 'User login name already exists',
                code_360: 'Home current configuration as the default configuration',
                code_361: 'EZVIZ appkey and secret information is not configured',
                code_362: 'The document category already exists',
                code_363: 'Not with the current user role',
                code_364: 'Non-admin role, lack of operating authority',
                code_365: 'The substation has no organization',
                code_366: 'The number of substations reaches the upper limit',
                code_367: 'The number of instruments reaches the upper limit',
                code_368: 'Without this substation',
                code_369: 'You can not find any information on the organization of the substation',
                code_370: 'admin user can not be disabled',
                code_371: 'You can not modify the admin user organization or role',
                code_372: 'All the user has not selected substation',
                code_373: 'The template and its subordinate template has been used in a substation',
                code_374: 'The substation number is out of range, can not be used to automatically generate',
                code_375: 'Present in the system numbered 10,109,999 substation, can not be automatically generated, please contact the administrator',
                code_376: 'In this substation, meter number at the gateway already exists',
                code_5000: 'The request failed server abnormal',
                code_377: 'The substation id available',
                code_378: 'The substation is unavailable id',
                code_379: 'Primary key of the record already exists',
                code_380: 'Equipment same name',
                code_381: 'The substation equipment is no packet',
                code_382: 'The current substation equipment under the same name already exists in the device grouping, proposed changes',
                code_other: 'Operation failed',
        };
}